### ISSUE TITLE
Artist name and Auth screen texts does not show on Pebble 2/ Pebble Steel

### ISSUE THREAD

**Issue by north20xx** [lourheroes/pebblify#6]
The authentification screen and artist name texts are not displayed for Pebble 2 / Pebble Steel watches.
This comes from multiple reports from Reddit.

Use a **Pebble 2** / **Pebble Steel**

**Auth screen**
Remove the app then install it again
1. Open the app
2. See that the Auth screen text does not show

**Now Playing screen**
1. Play a song in Spotify
2. Open the app
3. Go to the _Now Playing_ screen
4. See that the artist name does not show

**Expected behavior**
These texts should display on Pebble 2 / Pebble Steel watches. 

**Pebble watch :**
- Model: Pebble 2 / Pebble Steel
- PebbleOS version: /

**Smartphone:**
 - Device: /
 - OS: /

**Additional context**
It seems that PebbleJS Card's _body_ does not display on Pebble 2 / Pebble Steel.
Search from here

**Comment by enricorov** [comment]
Same issue seems to be present on Pebble Steel.

**Comment by lourheroes** [comment]
Thanks for the info! I updated the issue

**Comment by lourheroes** [comment]
> Same issue seems to be present on Pebble Steel.
Thanks for the info! I updated the issue

**Comment by north20xx** [comment]
> Same issue seems to be present on Pebble Steel.

Thanks for the info! I updated the issue

**Comment by enricorov** [comment]
This issue was fixed on my bugfix branch - [link](https://github.com/enricorov/pebblify/tree/bugfix-noTextOnBWScreens), if you want to take a look :)

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Geoff12889, @maxfaa, @richeshgupta, @lucaspestana, @davibc, @ParasSolanki, @PQCraft, @dirad, @Nidal-Bakir, @stepankuzmin, @error0x51, @levanhieu-git, @theale27, @GrinDeg, @zyp001a, @0xHexE, @ian7710, @anonpreet, @AcHsu104, @FloKla, @rachitmishra, @DPKCRZZ, @kristaponis, @LGX-65535-Dev, @mix1009, @Draggie306, @TripleK2004, @amoutonbrady, @michael-tm, @maxoidIO, @joaoeudes7, @The-MG, @wayne-hao, @amlitio, @JRS-Developer, @bertilxi, @wind39, @TODESENGEL1116, @Selene42, @AlexandrHoroshih, @binary1024, @catardif, @flowck, @saicharan0124, @SergiuAndreiV, @berkansivri, @mathew-yeap-lrn, @brnnnfx, @Ta180m, @dzshi96

**Comment by maxoux53** [comment]
hi guys, I just received this weird email with crypto stuff 🤔, and apparently it comes from/is linked to this repo...
![image](https://github.com/lourheroes/pebblify/assets/71935156/79d1eddf-cb8d-429f-a157-384c8ef3380b)
I don't understand, before this email popped out, I had never heard about "pebblify" (actually I still don't know what it is lol), so what am I doing here. that's really weird

**Comment by maxoux53** [comment]
(I've written here because when I click on "view it on Github", it opens this issue:)
![image](https://github.com/lourheroes/pebblify/assets/71935156/a6b17a44-f5bd-4563-af25-9fb518023abd)

**Comment by Draggie306** [comment]
> hi guys, I just received this weird email with crypto stuff 🤔, and apparently it comes from/is linked to this repo...

I got it too, probably just scammers being creative and misconfigured repo permissions
